spring:
  application:
    name: wise-task-task
  datasource:
    url: jdbc:postgresql://localhost:5432/${TASK_DB}
    username: ${TASK_DB_USER}
    password: ${TASK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.hibernate: ${LOGGING_LEVEL}
    ru.leti.wise.task.task: ${LOGGING_LEVEL}

grpc:
  service:
    graph:
      port: ${GRAPH_GRPC_PORT}
      host: localhost
    plugin:
      port: ${PLUGIN_GRPC_PORT}
      host: localhost
  port: ${TASK_GRPC_PORT}
server:
  port: ${TASK_PORT}

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
